export const LOAD_CHARACTERS_IN_PROGRESS = 'LOAD_CHARACTERS_IN_PROGRESS';
export const LOAD_CHARACTERS_SUCCESS = 'LOAD_CHARACTERS_SUCCESS';
export const LOAD_CHARACTERS_FAILURE = 'LOAD_CHARACTERS_FAILURE';
export const EDIT_LOAD_CHARACTERS = 'EDIT_LOAD_CHARACTERS';
export const SEARCH_CHARACTERS_IN_PROGRESS = 'SEARCH_CHARACTERS_IN_PROGRESS';
export const SEARCH_CHARACTERS_SUCCESS = 'SEARCH_CHARACTERS_SUCCESS';
export const SEARCH_CHARACTERS_FAILURE = 'SEARCH_CHARACTERS_FAILURE';
export const SCROLL_SEARCH_CHARACTERS_SUCCESS =
  'SCROLL_SEARCH_CHARACTERS_SUCCESS';
export const EDIT_SEARCH_CHARACTERS = 'EDIT_SEARCH_CHARACTERS';
export const SELECT_CHARACTER = 'SELECT_CHARACTER';
